function(get_package_version instr pname out_var)
    set(ver_regex "^${pname}-([0-9]+)\\.([0-9]+)\\.([0-9]+)$")
    string(REGEX REPLACE ${ver_regex} "\\1" vmaj ${instr})
    string(REGEX REPLACE ${ver_regex} "\\2" vmin ${instr})
    string(REGEX REPLACE ${ver_regex} "\\3" vpatch ${instr})
    set(${out_var}_VERSION_MAJOR ${vmaj} PARENT_SCOPE)
    set(${out_var}_VERSION_MINOR ${vmin} PARENT_SCOPE)
    set(${out_var}_VERSION_PATCH ${vpatch} PARENT_SCOPE)
    message(STATUS "${pname} ${vmaj}.${vmin}.${vpatch}")
endfunction()
